/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Alunos
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuConsulta = new javax.swing.JMenu();
        jMenuItemConsultaInfo = new javax.swing.JMenuItem();
        jMenuItemConsultaADM = new javax.swing.JMenuItem();
        jMenuMatricula = new javax.swing.JMenu();
        jMenuItemMatInfo = new javax.swing.JMenuItem();
        jMenuItemMatADM = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        jMenuConsulta.setText("Consulta");

        jMenuItemConsultaInfo.setText("Informática");
        jMenuItemConsultaInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaInfoActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItemConsultaInfo);

        jMenuItemConsultaADM.setText("Administração");
        jMenuItemConsultaADM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaADMActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItemConsultaADM);

        jMenuBar1.add(jMenuConsulta);

        jMenuMatricula.setText("Matrícula");

        jMenuItemMatInfo.setText("Informática");
        jMenuItemMatInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMatInfoActionPerformed(evt);
            }
        });
        jMenuMatricula.add(jMenuItemMatInfo);

        jMenuItemMatADM.setText("Administração");
        jMenuItemMatADM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMatADMActionPerformed(evt);
            }
        });
        jMenuMatricula.add(jMenuItemMatADM);

        jMenuBar1.add(jMenuMatricula);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemMatADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMatADMActionPerformed
        MatriculaAdm ma = new MatriculaAdm();
        jDesktopPane1.add(ma);
        ma.setVisible(true);
    }//GEN-LAST:event_jMenuItemMatADMActionPerformed

    private void jMenuItemConsultaInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaInfoActionPerformed
        ConsultaInformatica ci = new ConsultaInformatica();
        jDesktopPane1.add(ci);
        ci.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaInfoActionPerformed

    private void jMenuItemConsultaADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaADMActionPerformed
        ConsultaAdm ca = new ConsultaAdm();
        jDesktopPane1.add(ca);
        ca.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaADMActionPerformed

    private void jMenuItemMatInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMatInfoActionPerformed
        MatriculaInformatica mi = new MatriculaInformatica();
        jDesktopPane1.add(mi);
        mi.setVisible(true);
    }//GEN-LAST:event_jMenuItemMatInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsulta;
    private javax.swing.JMenuItem jMenuItemConsultaADM;
    private javax.swing.JMenuItem jMenuItemConsultaInfo;
    private javax.swing.JMenuItem jMenuItemMatADM;
    private javax.swing.JMenuItem jMenuItemMatInfo;
    private javax.swing.JMenu jMenuMatricula;
    // End of variables declaration//GEN-END:variables
}
